### ISSUE TITLE
Kindly update for android@7.0.0

### ISSUE THREAD

**Issue by GBoll** [winteragency/cordova-plugin-android-window-background#1]
I think the new path structure of cordova android@7.0.0 is breaking this plugin.
thx

**Comment by marcusforsberg** [comment]
Thanks for the heads-up. We'll take a look as soon as possible.

**Comment by marcusforsberg** [comment]
@GBoll I've pushed version 1.0.2 to npm now - can you please try it on cordova-android@7.0.0 and let me know if it works?
