### ISSUE TITLE
Plugin does not clean up platform changes when removed

### ISSUE THREAD

**Issue by markdon** [winteragency/cordova-plugin-android-window-background#2]
When removing this plugin with `cordova plugin remove cordova-plugin-android-window-background` the Android project can no longer build.

It appears the plugin has left behind modifications to android:theme in AndroidManifest.xml. 

Fixing this requires either a remove/add of the Android platform or manual modification of AndroidManifest.xml.

```
:processDebugResourcesC:\Projects\kudos-boards-pwa-cordova\platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml:28: AAPT: error: resource style/CordovaWindowBackgroundTheme (aka com.kudosboards.pwa:style/CordovaWindowBackgroundTheme) not found.

C:\Projects\kudos-boards-pwa-cordova\platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml:28: error: resource style/CordovaWindowBackgroundTheme (aka com.kudosboards.pwa:style/CordovaWindowBackgroundTheme) not found.
error: failed processing manifest.
```

**Comment by Fever905** [comment]
Yes super annoying as it now causes crashes in cordova 10.1.0

**Comment by markdon** [comment]
Having spent far more time than I would like developing with Cordova, I have learned that things like this are just something you have to live with. To mitigate problems like this, make sure you can remove your platforms and rebuild at any moment without any manual steps.
