### ISSUE TITLE
Doesn't work on Phonegap Build

### ISSUE THREAD

**Issue by abardik** [winteragency/cordova-plugin-android-window-background#4]
It doesn't work on Phonegap Build cli-7.1.0 (Android Cordova 6.3.0). After the following additions to config.xml the 1 second gray screen (before splashscreen) is still there.

```
<plugin name="cordova-plugin-android-window-background" spec="*">
	<variable name="WINDOW_BACKGROUND_COLOR" value="#0078d7" />
</plugin>
```

Also I tried to added the following, but with no effect:

```
<preference name="WINDOW_BACKGROUND_COLOR" value="#0078d7" />
```

**Comment by marcusforsberg** [comment]
Hi @abardik,

This plugin specifically only supports Android Cordova 7.x due to breaking changes introduced since 6.x. Please give it a go on the latest version and let us know if it's still an issue there. 🙂

**Comment by abardik** [comment]
Here is a fork with a translucent status bar. It works on Phonegap Build:
https://github.com/abardik/cordova-plugin-android-translucent-theme

Also you can use translucent navigation soft buttons:
`<item name="android:windowTranslucentNavigation">true</item>`

and background image instead of solid background color:
`<item name="android:windowBackground">@drawable/screen</item>`

where `drawable/screen.xml` should be like this:
```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
	<item>
		<color android:color="@color/cordova_window_background" />
	</item>
	<item>
		<bitmap android:src="@drawable/splash_screen_logo" android:tileMode="disabled" android:gravity="center" android:layout_gravity="center" />
	</item>
</layer-list>
```

(and you have to put splash_screen_logo.png to your /res/drawable).

Sorry, I had no time to make it configurable and make a PR, so just leave it here for the case.
